#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

extra_commands="info"

NEO4J="/opt/bin/neo4j"

depend() {
	need net
}

start() {
	ebegin "Starting neo4j"
	start-stop-daemon --start --quiet --exec ${NEO4J} start
	eend $?
}

stop() {
	ebegin "Stopping neo4j"
	${NEO4J} stop >/dev/null 2>&1
	eend $?
}

restart() {
	ebegin "Restarting neo4j"
	${NEO4J} restart >/dev/null 2>&1
	eend $?
}

info() {
	${NEO4J} info	
}
