#!/bin/sh

PATH="/usr/sbin:/usr/bin:/sbin:/bin"

j=0
for i in $(cat /movefs)
do
	mkdir "/${j}"
	mount --move "${i}" "/${j}"
	j=$(expr $j + 1)
done

zfs umount -a

for i in $(zpool list -H -o name)
do
	zpool export "$i"
done;
