# Override with:
# ssh -o PubkeyAuthentication=no -o PasswordAuthentication=yes -o PreferredAuthentications=password user@host
Host *
  ControlMaster auto
  ControlPath ~/.ssh/sockets/%r@%h-%p
  ControlPersist 3600
  Compression yes
  PasswordAuthentication no
  PreferredAuthentications publickey
