[cveDict]
	type = "http"
	url = "http://127.0.0.1:1323"

[ovalDict]
	type = "http"
	url = "http://127.0.0.1:1324"

[gost]
	type = "http"
	url = "http://127.0.0.1:1325"

#[exploit]
#	type = "http"
#	url = "http://127.0.0.1:1326"
