#!/bin/sh
PORTDIR=$(portageq envvar get_repo_path 2> /dev/null)
if [ -z "${PORTDIR}" ]; then
  PORTDIR=$(portageq envvar PORTDIR 2> /dev/null)
fi
if [ -d "${PORTDIR}"/.git ]; then
  rm -rf "${PORTDIR}"/.git
fi
