diff -Naur hcxdumptool-ebfcdf0243604d36dfac2757d4373bd9331b8a9a/Makefile hcxdumptool-ebfcdf0243604d36dfac2757d4373bd9331b8a9a-correct/Makefile
--- hcxdumptool-ebfcdf0243604d36dfac2757d4373bd9331b8a9a/Makefile	2018-08-05 00:08:59.110263256 +0000
+++ hcxdumptool-ebfcdf0243604d36dfac2757d4373bd9331b8a9a-correct/Makefile	2018-08-05 00:08:45.742262925 +0000
@@ -1,11 +1,12 @@
-INSTALLDIR	= /usr/local/bin
+PREFIX?=/usr/local
+INSTALLDIR	= $(DESTDIR)$(PREFIX)/bin
 
 HOSTOS := $(shell uname -s)
 GPIOSUPPORT=off
 
 CC	= gcc
-+CFLAGS ?= -O3 -Wall -Wextra
-+CFLAGS += -std=gnu99
+CFLAGS ?= -O3 -Wall -Wextra
+CFLAGS += -std=gnu99
 INSTFLAGS = -m 0755
 
 ifeq ($(HOSTOS), Linux)
@@ -14,7 +15,7 @@
 
 ifeq ($(GPIOSUPPORT), on)
 CFLAGS	+= -DDOGPIOSUPPORT
-LFLAGS	= -lwiringPi
+LDFLAGS	+= -lwiringPi
 endif
 
 
@@ -22,10 +23,10 @@
 
 build:
 ifeq ($(GPIOSUPPORT), on)
-	$(CC) $(CFLAGS) -o hcxpioff hcxpioff.c $(LFLAGS)
+	$(CC) $(CFLAGS) -o hcxpioff hcxpioff.c $(LDFLAGS)
 endif
 ifeq ($(HOSTOS), Linux)
-	$(CC) $(CFLAGS) -o hcxdumptool hcxdumptool.c -lpthread $(LFLAGS)
+	$(CC) $(CFLAGS) -o hcxdumptool hcxdumptool.c -lpthread $(LDFLAGS)
 endif
 
 
