--- Makefile.orig	2018-08-05 03:15:07.000000000 +0800
+++ Makefile	2018-08-05 08:51:38.858446712 +0800
@@ -1,4 +1,5 @@
-INSTALLDIR	= /usr/local/bin
+PREFIX?=/usr/local
+INSTALLDIR	= $(DESTDIR)$(PREFIX)/bin
 
 HOSTOS := $(shell uname -s)
 GPIOSUPPORT=off
@@ -14,7 +15,7 @@
 
 ifeq ($(GPIOSUPPORT), on)
 CFLAGS	+= -DDOGPIOSUPPORT
-LFLAGS	= -lwiringPi
+LDFLAGS	+= -lwiringPi
 endif
 
 
@@ -22,10 +23,10 @@
 
 build:
 ifeq ($(GPIOSUPPORT), on)
-	$(CC) $(CFLAGS) -o hcxpioff hcxpioff.c $(LFLAGS)
+	$(CC) $(CFLAGS) -o hcxpioff hcxpioff.c $(LDFLAGS)
 endif
 ifeq ($(HOSTOS), Linux)
-	$(CC) $(CFLAGS) -o hcxdumptool hcxdumptool.c -lpthread $(LFLAGS)
+	$(CC) $(CFLAGS) -o hcxdumptool hcxdumptool.c -lpthread $(LDFLAGS)
 endif
 
 
