# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
aho-corasick-0.7.15
ansi_term-0.11.0
atty-0.2.14
autocfg-1.0.1
bindgen-0.52.0
bitflags-1.2.1
cc-1.0.66
cexpr-0.3.6
cfg-if-0.1.10
clang-sys-0.28.1
clap-2.33.3
crossbeam-0.7.3
crossbeam-channel-0.4.4
crossbeam-deque-0.7.3
crossbeam-epoch-0.8.2
crossbeam-queue-0.2.3
crossbeam-utils-0.7.2
env_logger-0.7.1
glob-0.3.0
hermit-abi-0.1.18
humantime-1.3.0
lazy_static-1.4.0
lazycell-1.3.0
libc-0.2.82
libloading-0.5.2
log-0.4.13
maybe-uninit-2.0.0
memchr-2.3.4
memoffset-0.5.6
nom-4.2.3
peeking_take_while-0.1.2
proc-macro2-1.0.24
quick-error-1.2.3
quote-1.0.8
regex-1.4.3
regex-syntax-0.6.22
rustc-hash-1.1.0
scopeguard-1.1.0
shlex-0.1.1
strsim-0.8.0
syn-1.0.58
termcolor-1.1.2
textwrap-0.11.0
thiserror-1.0.23
thiserror-impl-1.0.23
thread_local-1.1.0
unicode-width-0.1.8
unicode-xid-0.2.1
vec_map-0.8.2
version_check-0.1.5
which-3.1.1
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Rust bindings for VirusTotal/yara"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/Hugal31/yara-rust"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 BSD-2-Clause BSD-3-Clause ISC MIT Unlicense"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
