# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
aho-corasick-0.7.15
ansi_term-0.11.0
atty-0.2.14
autocfg-1.0.1
bindgen-0.59.1
bitflags-1.3.2
bitvec-0.19.5
cexpr-0.5.0
cfg-if-0.1.10
cfg-if-1.0.0
clang-sys-1.3.0
clap-2.33.3
crossbeam-0.7.3
crossbeam-channel-0.4.4
crossbeam-deque-0.7.4
crossbeam-epoch-0.8.2
crossbeam-queue-0.2.3
crossbeam-utils-0.7.2
env_logger-0.8.4
funty-1.1.0
getrandom-0.2.3
glob-0.3.0
hermit-abi-0.1.19
humantime-2.1.0
lazy_static-1.4.0
lazycell-1.3.0
libc-0.2.107
libloading-0.7.1
log-0.4.14
maybe-uninit-2.0.0
memchr-2.3.4
memoffset-0.5.6
nom-6.2.1
peeking_take_while-0.1.2
ppv-lite86-0.2.15
proc-macro2-1.0.32
quote-1.0.10
radium-0.5.3
rand-0.8.4
rand_chacha-0.3.1
rand_core-0.6.3
rand_hc-0.3.1
redox_syscall-0.2.10
regex-1.4.6
regex-syntax-0.6.25
remove_dir_all-0.5.3
rustc-hash-1.1.0
scopeguard-1.1.0
shlex-1.1.0
strsim-0.8.0
syn-1.0.81
tap-1.0.1
tempfile-3.2.0
termcolor-1.1.2
textwrap-0.11.0
thiserror-1.0.30
thiserror-impl-1.0.30
unicode-width-0.1.9
unicode-xid-0.2.2
vec_map-0.8.2
version_check-0.9.3
wasi-0.10.2+wasi-snapshot-preview1
which-3.1.1
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
wyz-0.2.0
"

inherit cargo

DESCRIPTION="Rust bindings for VirusTotal/yara"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/Hugal31/yara-rust"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0 WITH LLVM-exception BSD-2-Clause BSD-3-Clause ISC MIT Unlicense"
SLOT="0"
KEYWORDS="~amd64 ~*"
IUSE=""

DEPEND=""
RDEPEND=""
