--- Makefile.orig	2018-08-03 23:09:11.000000000 +0800
+++ Makefile	2018-08-05 09:22:32.062571125 +0800
@@ -1,4 +1,5 @@
-INSTALLDIR	= /usr/local/bin
+PREFIX?=/usr/local
+INSTALLDIR	= $(DESTDIR)$(PREFIX)/bin
 
 HOSTOS := $(shell uname -s)
 
@@ -18,24 +19,24 @@
 all: build
 
 build:
-	$(CC) $(CFLAGS) -o hcxpcaptool hcxpcaptool.c -lz -lcrypto
-	$(CC) $(CFLAGS) -o hcxhashcattool hcxhashcattool.c -lcrypto -lpthread
-	$(CC) $(CFLAGS) -o wlanhc2hcx wlanhc2hcx.c
-	$(CC) $(CFLAGS) -o wlanwkp2hcx wlanwkp2hcx.c
-	$(CC) $(CFLAGS) -o wlanhcxinfo wlanhcxinfo.c
-	$(CC) $(CFLAGS) -o wlanhcx2cap wlanhcx2cap.c -lpcap
-	$(CC) $(CFLAGS) -o wlanhcx2essid wlanhcx2essid.c
-	$(CC) $(CFLAGS) -o wlanhcx2ssid wlanhcx2ssid.c
-	$(CC) $(CFLAGS) -o wlanhcxmnc wlanhcxmnc.c
-	$(CC) $(CFLAGS) -o wlanhashhcx wlanhashhcx.c
-	$(CC) $(CFLAGS) -o wlanhcxcat wlanhcxcat.c -lcrypto
-	$(CC) $(CFLAGS) -o wlanpmk2hcx wlanpmk2hcx.c -lcrypto
-	$(CC) $(CFLAGS) -o wlanjohn2hcx wlanjohn2hcx.c
-	$(CC) $(CFLAGS) -o wlancow2hcxpmk wlancow2hcxpmk.c
-	$(CC) $(CFLAGS) -o whoismac whoismac.c -lcurl
-	$(CC) $(CFLAGS) -o wlanhcx2john wlanhcx2john.c
-	$(CC) $(CFLAGS) -o wlanhcx2psk wlanhcx2psk.c -lcrypto
-	$(CC) $(CFLAGS) -o wlancap2wpasec wlancap2wpasec.c -lcurl
+	$(CC) $(CFLAGS) -o hcxpcaptool hcxpcaptool.c -lz -lcrypto $(LDFLAGS)
+	$(CC) $(CFLAGS) -o hcxhashcattool hcxhashcattool.c -lcrypto -lpthread  $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhc2hcx wlanhc2hcx.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanwkp2hcx wlanwkp2hcx.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcxinfo wlanhcxinfo.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcx2cap wlanhcx2cap.c -lpcap $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcx2essid wlanhcx2essid.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcx2ssid wlanhcx2ssid.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcxmnc wlanhcxmnc.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhashhcx wlanhashhcx.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcxcat wlanhcxcat.c -lcrypto $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanpmk2hcx wlanpmk2hcx.c -lcrypto $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanjohn2hcx wlanjohn2hcx.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlancow2hcxpmk wlancow2hcxpmk.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o whoismac whoismac.c -lcurl $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcx2john wlanhcx2john.c $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlanhcx2psk wlanhcx2psk.c -lcrypto $(LDFLAGS)
+	$(CC) $(CFLAGS) -o wlancap2wpasec wlancap2wpasec.c -lcurl $(LDFLAGS)
 
 
 install: build
