FROM pentoolinux/pentoo-core

# Setup repos
WORKDIR /var/db/repos/
# setup gentoo repo
RUN git clone https://github.com/gentoo/gentoo.git --depth 1
# setup pentoo repo
#RUN git clone https://github.com/pentoo/pentoo-overlay.git pentoo --depth 1
# Use the github checkout for pentoo, that's what we are testing
COPY . pentoo

#Regen doubles the time it takes for the action to run
#Revisit if this is worth running when we have >2 emerge calls
#RUN time FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox" emerge --regen --jobs=$(nproc) --quiet

WORKDIR /home

# disable minimal (pentoo-core is default minimal)
RUN sed -i 's# pentoo-minimal##' /etc/portage/make.conf

# Until we have a pentoo-ci to build from, add in the bdeps in the first step to avoid circular breakage
RUN goornogo="$(portageq match / 'dev-lang/go')"
RUN if [ -z "${goornogo}" ]; then \
      FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge -1 -kb dev-lang/go-bootstrap --jobs="$(nproc)" --load-average="$(nproc)" --quiet; \
      FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge -1 -kb dev-lang/go --jobs="$(nproc)" --load-average="$(nproc)" --quiet; \
    fi
RUN USE="-natspec" FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --with-bdeps=y --jobs="$(nproc)" --load-average="$(nproc)" --verbose --quiet app-arch/unzip
RUN USE="-verify-sig" FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --with-bdeps=y --jobs="$(nproc)" --load-average="$(nproc)" --verbose --quiet dev-build/automake
RUN FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --with-bdeps=y --jobs="$(nproc)" --load-average="$(nproc)" --verbose --quiet @world

# Check consistency of all metadata in the repo
RUN time FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --regen --jobs="$(nproc)" --quiet
# test install pentoo/pentoo
RUN time FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --getbinpkg=n --buildpkg=n --jobs=$(nproc) --load-average=$(nproc) --deep --update --newuse pentoo/pentoo --verbose --pretend
