FROM pentoolinux/pentoo-core-ci

# Setup repos
WORKDIR /var/db/repos/
# setup gentoo repo
RUN git clone https://github.com/gentoo/gentoo.git --depth 1
# setup pentoo repo
#RUN git clone https://github.com/pentoo/pentoo-overlay.git pentoo --depth 1
# Use the github checkout for pentoo, that's what we are testing
COPY . pentoo

#Regen doubles the time it takes for the action to run
#Revisit if this is worth running when we have >2 emerge calls
#RUN time FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox" emerge --regen --jobs=$(nproc) --quiet

WORKDIR /home

# Check consistency of all metadata in the repo
RUN time FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --regen --jobs="$(nproc)" --quiet
# test install pentoo/pentoo
RUN time FEATURES="-getbinpkg -ipc-sandbox -network-sandbox -pid-sandbox" emerge --getbinpkg=n --buildpkg=n --jobs=$(nproc) --load-average=$(nproc) --deep --update --newuse pentoo/pentoo --verbose --pretend
