#!/bin/sh
printf 'This script outputs firmware information in the format expected by /etc/genkernel.conf\n'
printf 'FIRMWARE_FILES="'
sudo dmesg | awk '/Loading firmware:/{print $7}' | sort -u | paste -sd ',' | tr -d '\n'
printf '"\n'
