# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8

CRATES="
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.102
	async-broadcast@0.7.2
	async-channel@2.5.0
	async-executor@1.14.0
	async-io@2.6.0
	async-lock@3.4.2
	async-process@2.5.0
	async-recursion@1.1.1
	async-signal@0.2.14
	async-task@4.7.1
	async-trait@0.1.89
	atomic-waker@1.1.2
	autocfg@1.5.1
	bitflags@2.11.1
	blocking@1.6.2
	bumpalo@3.20.3
	cfg-if@1.0.4
	clap@4.6.1
	clap_builder@4.6.0
	clap_derive@4.6.1
	clap_lex@1.1.0
	colorchoice@1.0.5
	concurrent-queue@2.5.0
	crossbeam-utils@0.8.21
	endi@1.1.1
	enumflags2@0.7.12
	enumflags2_derive@0.7.12
	equivalent@1.0.2
	errno@0.3.14
	event-listener-strategy@0.5.4
	event-listener@5.4.1
	fastrand@2.4.1
	foldhash@0.1.5
	futures-core@0.3.32
	futures-io@0.3.32
	futures-lite@2.6.1
	futures-task@0.3.32
	futures-util@0.3.32
	getrandom@0.4.2
	hashbrown@0.15.5
	hashbrown@0.17.1
	heck@0.5.0
	hermit-abi@0.3.9
	hermit-abi@0.5.2
	hex@0.4.3
	id-arena@2.3.0
	indexmap@2.14.0
	io-lifetimes@1.0.11
	is_terminal_polyfill@1.70.2
	itoa@1.0.18
	js-sys@0.3.99
	leb128fmt@0.1.0
	libc@0.2.186
	libudev-sys@0.1.4
	linux-raw-sys@0.12.1
	log@0.4.30
	memchr@2.8.0
	memoffset@0.9.1
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	ordered-stream@0.2.0
	parking@2.2.1
	pin-project-lite@0.2.17
	piper@0.2.5
	pkg-config@0.3.33
	polling@3.11.0
	prettyplease@0.2.37
	proc-macro-crate@3.5.0
	proc-macro2@1.0.106
	quote@1.0.45
	r-efi@6.0.0
	rustix@1.1.4
	rustversion@1.0.22
	semver@1.0.28
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	serde_repr@0.1.20
	signal-hook-registry@1.4.8
	slab@0.4.12
	strsim@0.11.1
	syn@2.0.117
	tempfile@3.27.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_edit@0.25.11+spec-1.1.0
	toml_parser@1.1.2+spec-1.1.0
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing@0.1.44
	udev@0.9.3
	uds_windows@1.2.1
	unicode-ident@1.0.24
	unicode-xid@0.2.6
	utf8parse@0.2.2
	uuid@1.23.1
	wasip2@1.0.3+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-macro-support@0.2.122
	wasm-bindgen-macro@0.2.122
	wasm-bindgen-shared@0.2.122
	wasm-bindgen@0.2.122
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	windows-link@0.2.1
	windows-sys@0.48.0
	windows-sys@0.61.2
	windows-targets@0.48.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
	winnow@1.0.3
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-bindgen@0.57.1
	wit-component@0.244.0
	wit-parser@0.244.0
	zbus@5.15.0
	zbus_macros@5.15.0
	zbus_names@4.3.2
	zmij@1.0.21
	zvariant@5.11.0
	zvariant_derive@5.11.0
	zvariant_utils@3.3.1
"

RUST_MIN_VER="1.87.0"
inherit cargo systemd

DESCRIPTION="Tells you what each USB cable / device on Linux can actually do. Rust port of WhatCable; previously published as \`whatcable\`."
HOMEPAGE="https://github.com/abrauchli/usbeehive"
SRC_URI="
	https://github.com/abrauchli/usbeehive/archive/refs/tags/v${PV}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" MIT Unicode-3.0 ZLIB"
SLOT="0"
KEYWORDS="~amd64"
IUSE="dbus"

RDEPEND="
	virtual/libudev:=
	dbus? ( sys-apps/dbus )
"
DEPEND="${RDEPEND}"
BDEPEND="
	virtual/pkgconfig
"
QA_FLAGS_IGNORED="
	usr/bin/usbeehive
	usr/bin/usbeehived
"

src_prepare() {
	eapply_user
	sed -i "s#%h/.cargo#/usr#" systemd/usbeehived.service || die
}

src_configure() {
	local myfeatures=(
		$(usev dbus)
	)
	cargo_src_configure
}

src_install() {
	cargo_src_install

	systemd_dounit systemd/usbeehived.service
	newinitd "${FILESDIR}/usbeehived.initd" usbeehived
}
